### ISSUE TITLE
WindowsでVOICEVOXだけ使う場合

### ISSUE THREAD

**Issue by k896951** [AlgosErgo/rinna_dialog#1]
WindowsでVOICEVOXだけ使うならこっちのコマンド使ってもらうと軽いかもしれません。
SeikaSay2との互換は無いのでちょっとあれですが。

 https://github.com/k896951/voxsay

**Comment by AlgosErgo** [comment]
教えて頂きありがとうございます！
AssistantSeikaだと毎回手動で起動しないといけないので、単体で動いて動作が軽くコマンドから使用できるのはとても有難いです。
